const sportsSet = [
  { question: "¿Qué deporte se juega con un disco en lugar de una pelota?", answer: "Hockey" },
  { question: "¿Qué deporte se practica sobre una tabla en el agua?", answer: "Surf" },
  { question: "¿En qué deporte se utiliza una raqueta y un volante?", answer: "Bádminton" },
  { question: "¿Qué deporte se juega con una pelota amarilla en una cancha de césped?", answer: "Tenis" },
  { question: "¿Qué deporte se juega con un balón ovalado?", answer: "Rugby" },
  { question: "¿Qué disciplina incluye salto con pértiga?", answer: "Atletismo" },
  { question: "¿Qué equipo ganó la Copa del Mundo en 2014?", answer: "Alemania" },
  { question: "¿Qué deporte se juega con bolas en una mesa?", answer: "Billar" },
  { question: "¿En qué deporte se utilizan anillas y barras paralelas?", answer: "Gimnasia artística" },
  { question: "¿Cuál es el jugador con más goles en la historia del fútbol?", answer: "Cristiano Ronaldo" },
  { question: "¿Qué jugador es conocido por su apodo 'Air Jordan'?", answer: "Michael Jordan" },
  { question: "¿Qué deporte es famoso por su modalidad 'freestyle' en el agua?", answer: "Esquí acuático" },
  { question: "¿Qué deporte incluye una prueba conocida como Ironman?", answer: "Triatlón" },
  { question: "¿En qué deporte se utiliza una pala para golpear la pelota sobre una mesa?", answer: "Tenis de mesa" },
  { question: "¿Cuál es el deporte más popular en los Estados Unidos?", answer: "Fútbol Americano" },
  { question: "¿Qué deporte tiene un evento conocido como 'Los X Games'?", answer: "Skateboarding" },
  { question: "¿Qué país ha ganado más veces los Juegos Olímpicos de Invierno?", answer: "Noruega" },
  { question: "¿En qué deporte se lanza una pelota pesada por un carril?", answer: "Bolos" },
  { question: "¿Qué deporte combina esquí y tiro con rifle?", answer: "Biatlón" },
  { question: "¿En qué deporte se realiza un 'swing'?", answer: "Golf" },
  { question: "¿Qué deportista es conocido por su habilidad en el snowboard?", answer: "Shaun White" },
  { question: "¿Qué deporte se juega con una pelota en un campo rectangular?", answer: "Fútbol" },
  { question: "¿Qué deporte es popular por su uso de patines de cuatro ruedas y contacto físico?", answer: "Roller derby" },
  { question: "¿Qué tipo deportes tiene como variante el curling?", answer: "Deportes de hielo" },
  { question: "¿Qué deporte tiene un evento anual llamado 'Tour de Francia'?", answer: "Ciclismo" },
  { question: "¿En qué deporte se utiliza una red elevada?", answer: "Voleibol" },
  { question: "¿Qué luchador es famoso por su movimiento 'La Roca Bottom'?", answer: "Dwayne Johnson" },
  { question: "¿Qué deporte consiste en combatir con espadas?", answer: "Esgrima" },
  { question: "¿Qué deporte se juega sobre caballos mientras se intenta golpear una bola?", answer: "Polo" },
  { question: "¿Qué deporte se practica en una piscina con coreografía?", answer: "Natación artística" }
];

const entertainmentSet = [
  { question: "¿Quién cantó la canción 'Thriller'?", answer: "Michael Jackson" },
  { question: "¿En qué película aparece el personaje de Darth Vader?", answer: "Star Wars" },
  { question: "¿Qué actor interpretó a Iron Man?", answer: "Robert Downey" },
  { question: "¿Qué artista pintó 'La noche estrellada'?", answer: "Vincent van Gogh" },
  { question: "¿Qué película ganó el Oscar a Mejor Película en 2019?", answer: "Parasite" },
  { question: "¿En qué ciudad se celebran los Premios Oscar?", answer: "Los Ángeles" },
  { question: "¿Qué famoso grupo musical cantó 'Hey Jude'?", answer: "The Beatles" },
  { question: "¿En qué serie aparece el personaje de Walter White?", answer: "Breaking Bad" },
  { question: "¿Qué serie tiene un personaje llamado 'Eleven'?", answer: "Stranger Things" },
  { question: "¿Qué película de Disney cuenta la historia de una sirena?", answer: "La Sirenita" },
  { question: "¿Qué actor interpretó a 'Spider-Man' en la película 'Capitán América: Civil War'?", answer: "Tom Holland" },
  { question: "¿Qué actor interpretó a Edward Scissorhands?", answer: "Johnny Depp" },
  { question: "¿Qué personaje dice la frase: 'Tonto es el que hace tonterías'?", answer: "Forrest Gump" },
  { question: "¿Qué cantante es conocido como el 'Rey del Reggaetón'?", answer: "Daddy Yankee" },
  { question: "¿Qué cantante tiene el apodo de 'La Reina del Pop'?", answer: "Madonna" },
  { question: "¿En qué serie Benedict Cumberbatch interpreta a un detective?", answer: "Sherlock Holmes" },
  { question: "¿Qué banda canta la canción 'Bohemian Rhapsody'?", answer: "Queen" },
  { question: "¿Qué personaje animado vive en una piña?", answer: "Bob Esponja" },
  { question: "¿En qué película animada se presenta el personaje 'Miguel' que ama la música?", answer: "Coco" },
  { question: "¿Qué serie se desarrolla en un hospital en Seattle?", answer: "Anatomía de Grey" },
  { question: "¿Qué película animada tiene juguetes que cobran vida?", answer: "Toy Story" },
  { question: "¿Qué casa representa Harry Potter en Hogwarts?", answer: "Gryffindor" },
  { question: "¿Qué cantante popularizó la canción 'Shape of You'?", answer: "Ed Sheeran" },
  { question: "¿Qué película de Disney tiene una reina del hielo llamada Elsa?", answer: "Frozen" },
  { question: "¿Qué director de cine dirigió 'Jurassic Park'?", answer: "Steven Spielberg" },
  { question: "¿Qué cantante interpretó 'Rolling in the Deep'?", answer: "Adele" },
  { question: "¿Qué película tiene a un burro que habla?", answer: "Shrek" },
  { question: "¿Qué saga literaria y cinematográfica presenta a Katniss Everdeen?", answer: "Los Juegos del Hambre" },
  { question: "¿Qué comediante protagoniza la serie 'El Príncipe del Rap'?", answer: "Will Smith" },
  { question: "¿Qué película musical cuenta la historia de P.T. Barnum?", answer: "The Greatest Showman" }
];

const artSet = [
  { question: "¿Quién pintó 'La Mona Lisa'?", answer: "Leonardo da Vinci" },
  { question: "¿Qué movimiento artístico está relacionado con la geometría y formas abstractas?", answer: "Cubismo" },
  { question: "¿Qué escultor hizo el 'David' en mármol?", answer: "Miguel Ángel" },
  { question: "¿En qué museo se encuentra la pintura 'La Gioconda'?", answer: "Museo del Louvre" },
  { question: "¿En qué ciudad se encuentra la Sagrada Familia, diseñada por Gaudí?", answer: "Barcelona" },
  { question: "¿Quién pintó 'Guernica'?", answer: "Pablo Picasso" },
  { question: "¿Dónde se encuentra el Museo del Prado?", answer: "Madrid" },
  { question: "¿Qué pintor español es famoso por sus grabados oscuros?", answer: "Francisco de Goya" },
  { question: "¿Qué estilo artístico está relacionado con emociones intensas y pinceladas visibles?", answer: "Expresionismo" },
  { question: "¿Quién pintó 'La persistencia de la memoria'?", answer: "Salvador Dalí" },
  { question: "¿Qué obra pintó Botticelli que representa el nacimiento de una diosa?", answer: "El nacimiento de Venus" },
  { question: "¿Qué pintor es conocido por 'La joven de la perla'?", answer: "Johannes Vermeer" },
  { question: "¿Qué artista mexicano creó numerosos autorretratos con simbolismo?", answer: "Frida Kahlo" },
  { question: "¿Qué pintor impresionista francés hizo 'Impresión, sol naciente'?", answer: "Claude Monet" },
  { question: "¿Quién pintó 'El grito'?", answer: "Edvard Munch" },
  { question: "¿Qué pintor italiano es conocido por 'La escuela de Atenas'?", answer: "Rafael" },
  { question: "¿Qué artista fue un pionero del arte abstracto con obras como 'Composición VIII'?", answer: "Wassily Kandinsky" },
  { question: "¿Qué pintor holandés es conocido por sus autorretratos y 'La noche estrellada'?", answer: "Vincent van Gogh" },
  { question: "¿Qué autor pintó 'El jardín de las delicias'?", answer: "El Bosco" },
  { question: "¿Qué escultor es conocido por 'El pensador'?", answer: "Auguste Rodin" },
  { question: "¿Qué pintor francés es famoso por escenas de bailarinas?", answer: "Edgar Degas" },
  { question: "¿En qué ciudad se encuentra el MoMA, famoso museo de arte moderno?", answer: "Nueva York" },
  { question: "¿Qué pintor del barroco es famoso por su uso del claroscuro?", answer: "Caravaggio" },
  { question: "¿Qué movimiento artístico se caracteriza por lo onírico y lo irracional?", answer: "Surrealismo" },
  { question: "¿Qué pintor es conocido por 'El almuerzo de los remeros'?", answer: "Pierre-Auguste Renoir" },
  { question: "¿Qué arquitecto diseñó la Casa Batlló y el Parque Güell?", answer: "Antoni Gaudí" },
  { question: "¿Qué artista contemporáneo es conocido por esculturas de globos metálicos?", answer: "Jeff Koons" },
  { question: "¿Qué pintor flamenco es conocido por sus retratos como 'El matrimonio Arnolfini'?", answer: "Jan van Eyck" },
  { question: "¿Qué artista es famoso por sus latas de sopa Campbell?", answer: "Andy Warhol" },
  { question: "¿Qué pintor surrealista es conocido por retratar elefantes con patas largas y delgadas?", answer: "Salvador Dalí" }
];

const scienceSet = [
  { question: "¿Qué elemento químico tiene el símbolo H?", answer: "Hidrógeno" },
  { question: "¿Qué planeta es el más cercano al sol?", answer: "Mercurio" },
  { question: "¿Qué gas respiramos principalmente?", answer: "Oxígeno" },
  { question: "¿Qué fuerza atrae los objetos hacia la Tierra?", answer: "Gravedad" },
  { question: "¿Qué órgano bombea la sangre?", answer: "Corazón" },
  { question: "¿Cómo se llama el proceso en el cual las plantas fabrican su alimento?", answer: "Fotosíntesis" },
  { question: "¿Qué tipo de animal es un delfín?", answer: "Mamífero" },
  { question: "¿Qué es la célula?", answer: "Unidad" },
  { question: "¿Quién formuló la teoría de la relatividad?", answer: "Albert Einstein" },
  { question: "¿Qué metal es líquido a temperatura ambiente?", answer: "Mercurio" },
  { question: "¿Qué partícula tiene carga negativa?", answer: "Electrón" },
  { question: "¿Qué es el ADN?", answer: "Ácido desoxirribonucleico" },
  { question: "¿Qué planeta tiene los anillos más grandes?", answer: "Saturno" },
  { question: "¿Quién descubrió la penicilina?", answer: "Alexander Fleming" },
  { question: "¿Qué gas es necesario para la respiración?", answer: "Oxígeno" },
  { question: "¿Qué instrumento mide la temperatura?", answer: "Termómetro" },
  { question: "¿Qué tipo de estrella es el Sol?", answer: "Amarilla" },
  { question: "¿Cuál es el órgano más grande del cuerpo humano?", answer: "Piel" },
  { question: "¿Qué músculo permite respirar?", answer: "Diafragma" },
  { question: "¿Qué tipo de energía se produce a partir del viento?", answer: "Eólica" },
  { question: "¿Qué elemento químico tiene el símbolo K?", answer: "Potasio" },
  { question: "¿Qué es un átomo?", answer: "Partícula" },
  { question: "¿Qué animal tiene el cerebro más grande?", answer: "Delfín" },
  { question: "¿Qué planeta tiene la luna más grande?", answer: "Júpiter" },
  { question: "¿Cómo se llama la capa externa de la Tierra?", answer: "Corteza" },
  { question: "¿Qué tipo de animal pone huevos?", answer: "Ave" },
  { question: "¿Qué instrumento se usa para escuchar el corazón?", answer: "Estetoscopio" },
  { question: "¿En qué estado se encuentra el agua a 100 grados Celsius?", answer: "Gas" },
  { question: "¿Qué científico propuso las leyes del movimiento?", answer: "Isaac Newton" },
  { question: "¿Qué parte del ojo controla la cantidad de luz que entra?", answer: "Pupila" }
];

const historySet = [
  { question: "¿En qué año llegó Cristóbal Colón a América?", answer: "1492" },
  { question: "¿Quién fue el primer presidente de Estados Unidos?", answer: "Washington" },
  { question: "¿Qué país fue el primero en enviar un hombre a la luna?", answer: "EE.UU." },
  { question: "¿En qué año terminó la Segunda Guerra Mundial?", answer: "1945" },
  { question: "¿Qué civilización construyó las pirámides?", answer: "Egipcia" },
  { question: "¿Quién fue el líder de la Revolución Francesa?", answer: "Robespierre" },
  { question: "¿Qué emperador romano fue conocido por su gran ejército?", answer: "Juliano" },
  { question: "¿Qué país fue el primero en abolir la esclavitud?", answer: "Haití" },
  { question: "¿Qué acontecimiento marcó el fin del Imperio Romano?", answer: "Caída" },
  { question: "¿En qué año cayó el Muro de Berlín?", answer: "1989" },
  { question: "¿Qué dictador gobernó Chile entre 1973 y 1990?", answer: "Pinochet" },
  { question: "¿Qué país sufrió la Revolución de Octubre?", answer: "Rusia" },
  { question: "¿Quién fue el primer faraón de Egipto?", answer: "Narmer" },
  { question: "¿En qué ciudad se firmó la Declaración de Independencia de EE.UU.?", answer: "Filadelfia" },
  { question: "¿Qué evento histórico ocurrió en 1776 en EE.UU.?", answer: "Independencia" },
  { question: "¿Quién fue el líder de la independencia de México?", answer: "Hidalgo" },
  { question: "¿Qué guerra se libró entre 1914 y 1918?", answer: "Primera Guerra Mundial" },
  { question: "¿Qué imperio fundó Alejandro Magno?", answer: "Macedonio" },
  { question: "¿Qué civilización construyó Machu Picchu?", answer: "Inca" },
  { question: "¿Quién fue el líder del imperio mongol?", answer: "Gengis Khan" },
  { question: "¿Quién fue el último zar de Rusia?", answer: "Nicolás II" },
  { question: "¿En qué batalla fue derrotado Napoleón Bonaparte?", answer: "Waterloo" },
  { question: "¿Qué país fue invadido en la Guerra de las Malvinas?", answer: "Argentina" },
  { question: "¿Qué país se independizó de España en 1810?", answer: "México" },
  { question: "¿Qué general fue derrotado en la Batalla de Waterloo?", answer: "Napoleón" },
  { question: "¿Qué conflicto marcó el inicio de la guerra fría?", answer: "Segunda Guerra Mundial" },
  { question: "¿Quién fue el líder del movimiento de derechos civiles en EE.UU.?", answer: "Martin Luther King" },
  { question: "¿A qué rey apodaban como 'El Grande?", answer: "Carlomagno" },
  { question: "¿En qué año comenzó la Revolución Industrial?", answer: "1760" },
  { question: "¿Qué país lideró la colonización de África en el siglo XIX?", answer: "Reino Unido" }
];

const geographySet = [
  { question: "¿Cuál es la capital de Canadá?", answer: "Ottawa" },
  { question: "¿Qué río atraviesa El Cairo?", answer: "Nilo" },
  { question: "¿Qué país europeo tiene más lagos naturales?", answer: "Finlandia" },
  { question: "¿Cuál es el continente con menor población?", answer: "Antártida" },
  { question: "¿En qué país se encuentra el desierto del Gobi?", answer: "Mongolia" },
  { question: "¿Cuál es la capital de Australia?", answer: "Canberra" },
  { question: "¿Qué país limita con más países en el mundo?", answer: "China" },
  { question: "¿Cuál es la montaña más alta de África?", answer: "Kilimanjaro" },
  { question: "¿En qué país se encuentra la ciudad de Dubái?", answer: "Emiratos Árabes Unidos" },
  { question: "¿Qué cordillera atraviesa América del Norte?", answer: "Montañas Rocosas" },
  { question: "¿Qué mar está al este de Italia?", answer: "Mar Adriático" },
  { question: "¿Cuál es la capital de Sudáfrica?", answer: "Pretoria" },
  { question: "¿Qué isla es famosa por sus estatuas moáis?", answer: "Isla de Pascua" },
  { question: "¿Qué país sudamericano no tiene salida al mar?", answer: "Bolivia" },
  { question: "¿Qué estrecho separa Asia de América?", answer: "Estrecho de Bering" },
  { question: "¿Cuál es la capital de Tailandia?", answer: "Bangkok" },
  { question: "¿Qué país tiene el mayor número de husos horarios?", answer: "Francia" },
  { question: "¿En qué país se encuentra el monte Fuji?", answer: "Japón" },
  { question: "¿Qué lago es el más profundo del mundo?", answer: "Baikal" },
  { question: "¿Qué país es conocido por su forma de hoja de arce?", answer: "Canadá" },
  { question: "¿Cuál es la capital de Marruecos?", answer: "Rabat" },
  { question: "¿Qué cadena montañosa separa Francia de España?", answer: "Pirineos" },
  { question: "¿Qué país alberga la selva de Borneo?", answer: "Indonesia" },
  { question: "¿En qué país se encuentran las ruinas de Petra?", answer: "Jordania" },
  { question: "¿Qué capital europea está dividida por el río Danubio?", answer: "Budapest" },
  { question: "¿Qué país tiene la costa más larga del mundo?", answer: "Canadá" },
  { question: "¿Qué ciudad es famosa por su torre inclinada?", answer: "Pisa" },
  { question: "¿Cuál es el país más pequeño del mundo?", answer: "Vaticano" },
  { question: "¿Qué desierto es el más grande del planeta?", answer: "Antártico" },
  { question: "¿Qué canal de navegación esta ubicado entre el mar Caribe y el océano Pacífico?", answer: "Canal de Panamá" }
];

const literatureSet = [
  { question: "¿Quién escribió el libro de 'Harry Potter'?", answer: "Rowling" },
  { question: "¿Quién es el autor de 'Don Quijote'?", answer: "Miguel de Cervantes" },
  { question: "¿Quién escribió 'El Principito'?", answer: "Saint-Exupéry" },
  { question: "¿Quién escribió 'Alicia en el País de las Maravillas'?", answer: "Lewis Carroll" },
  { question: "¿Qué autor escribió 'Matilda'?", answer: "Roald Dahl" },
  { question: "¿Quién escribió la historia de 'Peter Pan'?", answer: "Barrie" },
  { question: "¿Qué autor escribió 'Romeo y Julieta'?", answer: "Shakespeare" },
  { question: "¿Quién escribió 'La isla del tesoro'?", answer: "Robert Louis Stevenson" },
  { question: "¿Qué autor escribió 'Drácula'?", answer: "Bram Stoker" },
  { question: "¿Quién escribió '20.000 leguas de viaje submarino'?", answer: "Julio Verne" },
  { question: "¿Qué autor escribió 'Moby Dick'?", answer: "Herman Melville" },
  { question: "¿Quién creó el personaje de 'Tom Sawyer'?", answer: "Mark Twain" },
  { question: "¿Quién escribió la historia de 'Frankenstein'?", answer: "Mary Shelley" },
  { question: "¿Qué autor escribió 'Matar a un ruiseñor'?", answer: "Harper Lee" },
  { question: "¿Quién escribió 'El Gran Gatsby'?", answer: "Scott Fitzgerald" },
  { question: "¿Qué autor escribió '1984'?", answer: "George Orwell" },
  { question: "¿Quién escribió 'La metamorfosis'?", answer: "Franz Kafka" },
  { question: "¿Qué autor escribió 'Crimen y castigo'?", answer: "Dostoyevski" },
  { question: "¿Quién escribió 'La casa de los espíritus'?", answer: "Isabel Allende" },
  { question: "¿Quién escribió 'El retrato de Dorian Gray'?", answer: "Oscar Wilde" },
  { question: "¿Qué autor escribió 'Corazón'?", answer: "Edmondo De Amicis" },
  { question: "¿Quién escribió el cuento 'El patito feo'?", answer: "Hans Christian Andersen" },
  { question: "¿Quién escribió 'Heidi'?", answer: "Johanna Spyri" },
  { question: "¿Quién escribió 'Caperucita Roja'?", answer: "Charles Perrault" },
  { question: "¿Qué autor escribió 'El mago de Oz'?", answer: "Frank Baum" },
  { question: "¿Quién escribió 'El jardín secreto'?", answer: "Frances Hodgson Burnett" },
  { question: "¿Qué autor escribió 'Las aventuras de Pinocho'?", answer: "Carlo Collodi" },
  { question: "¿Quién escribió 'Los miserables'?", answer: "Victor Hugo" },
  { question: "¿Quién escribió 'Cien años de soledad'?", answer: "Gabriel García Márquez" },
  { question: "¿Quién escribió 'Fahrenheit 451'?", answer: "Ray Bradbury" }
];

const musicSet = [
  { question: "¿Quién es conocido como el 'Rey del Pop'?", answer: "Michael Jackson" },
  { question: "¿Qué banda cantó 'Bohemian Rhapsody'?", answer: "Queen" },
  { question: "¿Qué cantante es famoso por 'Like a Rolling Stone'?", answer: "Bob Dylan" },
  { question: "¿Quién cantó 'I Will Always Love You'?", answer: "Whitney Houston" },
  { question: "¿Qué cantante es conocida como la 'Reina del Pop'?", answer: "Madonna" },
  { question: "¿Qué grupo británico es conocido por 'Wonderwall'?", answer: "Oasis" },
  { question: "¿Qué cantante popularizó la canción 'Happy'?", answer: "Pharrell Williams" },
  { question: "¿Qué banda lanzó el álbum 'A Rush of Blood to the Head'?", answer: "Coldplay" },
  { question: "¿Qué grupo es famoso por la canción 'Zombie'?", answer: "The Cranberries" },
  { question: "¿Quién cantó 'Rehab'?", answer: "Amy Winehouse" },
  { question: "¿Qué banda canta 'Radioactive'?", answer: "Imagine Dragons" },
  { question: "¿Quién canta 'Shivers'?", answer: "Ed Sheeran" },
  { question: "¿Qué grupo lanzó 'Boulevard of Broken Dreams'?", answer: "Green Day" },
  { question: "¿Qué cantante es conocida por 'Waka Waka'?", answer: "Shakira" },
  { question: "¿Quién canta 'Locked Out of Heaven'?", answer: "Bruno Mars" },
  { question: "¿Qué artista canta 'Provenza'?", answer: "Karol G" },
  { question: "¿Qué artista canta 'Stayin' Alive'?", answer: "Bee Gees" },
  { question: "¿Qué banda lanzó 'Welcome to the Jungle'?", answer: "Guns N' Roses" },
  { question: "¿Quién interpretó el tema de James Bond 'Skyfall'?", answer: "Adele" },
  { question: "¿Qué grupo canta 'Take on Me'?", answer: "A-ha" },
  { question: "¿Qué banda canta 'Mr. Brightside'?", answer: "The Killers" },
  { question: "¿Quién interpreta 'As It Was'?", answer: "Harry Styles" },
  { question: "¿Quién canta 'Dance Monkey'?", answer: "Tones and I" },
  { question: "¿Qué grupo canta 'Counting Stars'?", answer: "OneRepublic" },
  { question: "¿Quién canta 'Levitating'?", answer: "Dua Lipa" },
  { question: "¿Qué cantante lanzó 'Flowers' en 2023?", answer: "Miley Cyrus" },
  { question: "¿Qué artista mexicano canta 'Adiós amor'?", answer: "Christian Nodal" },
  { question: "¿Quién es el vocalista principal de U2?", answer: "Bono" },
  { question: "¿Qué banda compuso 'Smells Like Teen Spirit'?", answer: "Nirvana" },
  { question: "¿Quién es la cantante de 'Bad Romance'?", answer: "Lady Gaga" }
];

const cinemaSet = [
  { question: "¿Quién dirigió 'Jurassic Park'?", answer: "Steven Spielberg" },
  { question: "¿Qué actor interpretó a Jack Sparrow?", answer: "Johnny Depp" },
  { question: "¿Quién protagonizó 'Forrest Gump'?", answer: "Tom Hanks" },
  { question: "¿En qué película aparece el personaje de Darth Vader?", answer: "Star Wars" },
  { question: "¿Quién dirigió 'Titanic'?", answer: "James Cameron" },
  { question: "¿En qué película aparece el personaje de Gollum?", answer: "El Señor de los Anillos" },
  { question: "¿Qué película ganó el Oscar a Mejor Película en 1994?", answer: "Forrest Gump" },
  { question: "¿Quién interpretó a 'Rocky Balboa'?", answer: "Sylvester Stallone" },
  { question: "¿Qué película tiene como protagonista a un tiburón gigante?", answer: "Jaws" },
  { question: "¿Quién dirigió 'Pulp Fiction'?", answer: "Quentin Tarantino" },
  { question: "¿Qué actor interpreta a 'Deadpool'?", answer: "Ryan Reynolds" },
  { question: "¿En qué película aparece el personaje de 'El Joker'?", answer: "Batman" },
  { question: "¿Qué película de Pixar tiene a un robot llamado Wall-E?", answer: "Wall-E" },
  { question: "¿Qué actor interpretó a 'El Capitán América'?", answer: "Chris Evans" },
  { question: "¿Qué película de ciencia ficción fue dirigida por Ridley Scott?", answer: "Alien" },
  { question: "¿Qué actor interpretó a 'Spiderman' de 2002?", answer: "Tobey Maguire" },
  { question: "¿Quién protagonizó 'El Lobo de Wall Street'?", answer: "Leonardo DiCaprio" },
  { question: "¿Qué actor interpreta a Wolverine?", answer: "Hugh Jackman" },
  { question: "¿En qué película aparece el personaje de 'Scarlett O'Hara'?", answer: "Lo que el viento se llevó" },
  { question: "¿Qué película de Marvel presenta a los Vengadores?", answer: "Los Vengadores" },
  { question: "¿Qué película animada tiene como protagonista a Simba?", answer: "El Rey León" },
  { question: "¿Qué película de ciencia ficción fue dirigida por Christopher Nolan?", answer: "Interstellar" },
  { question: "¿En qué película aparece el personaje de 'The Dude'?", answer: "El Gran Lebowski" },
  { question: "¿Qué película tiene un personaje llamado 'Hannibal Lecter'?", answer: "El Silencio de los Corderos" },
  { question: "¿Qué actor interpretó a 'Indiana Jones'?", answer: "Harrison Ford" },
  { question: "¿Quién fue el director de 'El Resplandor'?", answer: "Stanley Kubrick" },
  { question: "¿Qué actor interpreta al personaje de 'The Terminator'?", answer: "Arnold Schwarzenegger" },
  { question: "¿Qué película de animación tiene como protagonista a un pez llamado Nemo?", answer: "Buscando a Nemo" },
  { question: "¿Qué película musical tiene como protagonista a Danny y Sandy?", answer: "Grease" },
  { question: "¿En qué película aparece el personaje de Tyler Durden?", answer: "El Club de la Pelea" }
];


export const topicSets = [
  sportsSet,
  entertainmentSet,
  artSet,
  scienceSet,
  historySet,
  geographySet,
  literatureSet,
  musicSet,
  cinemaSet
]